# Generated by Django 3.2.7 on 2021-09-21 08:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('malade', '0002_auto_20210921_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profile_all')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, unique=True)),
                ('maladie', models.CharField(max_length=200)),
                ('date_heur_A', models.DateTimeField()),
                ('date_heur_d', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Malades',
        ),
    ]
